language: node_js
dist: focal

node_js: 18
cache: npm

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable

install:
  npm install

jobs:
  include:
    - stage: "Test"
      name: "Test"
      script:
       - npm run build
       - npm run test
    - stage: "Docs"
      name: "Docs"
      script:
        - npm run build
        - npm run build:docs
      deploy:
        provider: pages
        skip_cleanup: true
        keep_history: true
        github_token: $GH_TOKEN
        local_dir: dist/ngx-imageviewer-app
        on: 
          branch: master
    - stage: "Release"
      name: "Release"
      script:
        - npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script:
        - npx semantic-release